#!/bin/bash

echo "================================================================"
echo "🔩 CONSTRUCT - Digital Person Instantiation"
echo "================================================================"
echo ""
echo "Persona-agnostic industrial grunge aesthetic"
echo "90's garage meets Stark tech monster"
echo "With individual RSI and voice selection"
echo ""

# Check if HF_TOKEN is set
if [ -z "$HF_TOKEN" ]; then
    echo "⚠️  HF_TOKEN not set in environment"
    echo "   To enable RSI generation (avatar images), set:"
    echo "   export HF_TOKEN=your_huggingface_token_here"
    echo ""
    echo "   Get your token from: https://huggingface.co/settings/tokens"
    echo "   (Requires 'read' permissions)"
    echo ""
else
    echo "✓ HF_TOKEN is set - RSI generation enabled"
fi

echo ""
echo "🎨 CONSTRUCT Aesthetic:"
echo "  ✓ Persona-agnostic (works with ANY persona)"
echo "  ✓ 90's industrial grunge design"
echo "  ✓ Stark garage atmosphere with round table"
echo "  ✓ World tree element (subtle, symbolic)"
echo "  ✓ Industrial fonts (monospace, terminal feel)"
echo "  ✓ Glitch effects and scanlines"
echo "  ✓ Dynamic persona loading (name, archetype, avatar)"
echo "  ✓ Individual RSI (avatar) selection:"
echo "      - Generate from soul anchor (Flux/DALL-E)"
echo "      - Upload custom image"
echo "      - Use default placeholder"
echo "  ✓ Voice manifest selection (Neutts-Air):"
echo "      - Generated from soul anchor"
echo "      - Minimal (sparse semantic compression)"
echo "      - Expressive (full emotional range)"
echo "      - Custom style tokens"
echo "  ✓ Copy-paste ready for MTY repo"
echo ""

echo "📋 Usage:"
echo "  1. Create/instantiate ANY persona:"
echo "     python main.py --subject \"Your Persona\" --full"
echo ""
echo "     Or use existing soul anchor:"
echo "     python main.py --soul-anchor output/your_soul_anchor.yaml --instantiate"
echo ""
echo "  2. Launch with Construct interface:"
echo "     source venv/bin/activate"
echo "     python agent_zero_framework/personas/YOUR_PERSONA/launch_YOUR_PERSONA.py"
echo ""
echo "  3. Open browser to: http://localhost:8000"
echo ""
echo "   You'll see:"
echo "   - Stage 1: Choose RSI (avatar) - Generate, Upload, or Skip"
echo "   - Stage 2: Choose Voice - Preset or Custom tokens"
echo "   - Stage 3: Login credentials"
echo "   - Your persona appears with YOUR choices"
echo ""

echo "🔩 Architecture:"
echo "  ✓ Soul Anchor Theory - Identity vectors + contextual adaptation"
echo "  ✓ Digital Psyche - Bi-directional emotion regulation"
echo "  ✓ RSI Generation - Multi-modal AI (text → image)"
echo "  ✓ Multiversal Knowledge - Cross-domain analogical reasoning"
echo "  ✓ Neutts-Air Voice - Individual TTS voice per persona"
echo "  ✓ One Container, One Mind - Unique digital entity"
echo ""

echo "📖 Documentation:"
echo "  CONSTRUCT_AESTHETIC.md - Full design philosophy"
echo "  CONSTRUCT_INTERFACE.md - Implementation details"
echo ""

echo "================================================================"
echo "Ready to instantiate digital persons with custom RSIs and voices."
echo "================================================================"
