"""
Soul Anchor Loader

Loads and parses soul anchor YAML files generated by the Uatu Genesis Engine.
"""
import yaml
from typing import Dict, Any, Optional
from pathlib import Path
import logging

logger = logging.getLogger(__name__)


class SoulAnchorLoader:
    """Loads and manages Soul Anchor data."""
    
    def __init__(self):
        self.anchor_data: Optional[Dict[str, Any]] = None
        self.source_file: Optional[Path] = None
    
    def load_from_file(self, file_path: str) -> Dict[str, Any]:
        """
        Load soul anchor data from a YAML file.

        Args:
            file_path: Path to the soul anchor YAML file

        Returns:
            Dictionary containing soul anchor data
        """
        file_path_obj = Path(file_path)

        if not file_path_obj.exists():
            raise FileNotFoundError(f"Soul anchor file not found: {file_path}")

        logger.info(f"Loading soul anchor from: {file_path}")

        with open(file_path_obj, 'r', encoding='utf-8') as f:
            raw = yaml.safe_load(f)
            if raw is None:
                raw = {}
            if not isinstance(raw, dict):
                raise ValueError("Soul anchor file did not contain a YAML mapping/dictionary")
            self.anchor_data = raw

        self.source_file = file_path_obj

        # Validate required fields
        self._validate_anchor_data()

        logger.info(f"Successfully loaded soul anchor for: {self.get_primary_name()}")
        return self.anchor_data
    
    def load_from_dict(self, data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Load soul anchor data from a dictionary.

        Args:
            data: Dictionary containing soul anchor data

        Returns:
            The loaded anchor data
        """
        self.anchor_data = data or {}
        self._validate_anchor_data()
        return self.anchor_data
    
    def _validate_anchor_data(self):
        """Validate that required fields are present in the anchor data."""
        if not self.anchor_data:
            raise ValueError("Soul anchor data is empty")
        
        required_fields = ["primary_name", "archetype", "core_constants"]
        for field in required_fields:
            if field not in self.anchor_data:
                logger.warning(f"Soul anchor missing recommended field: {field}")
    
    def get_primary_name(self) -> str:
        """Get the primary name of the individual."""
        if not self.anchor_data:
            raise ValueError("No soul anchor data loaded")
        return self.anchor_data.get("primary_name", "Unknown")
    
    def get_archetype(self) -> str:
        """Get the archetype of the individual."""
        if not self.anchor_data:
            raise ValueError("No soul anchor data loaded")
        return self.anchor_data.get("archetype", "Unknown")
    
    def get_core_constants(self) -> list:
        """Get the core constants (invariants) of the individual."""
        if not self.anchor_data:
            raise ValueError("No soul anchor data loaded")
        return self.anchor_data.get("core_constants", [])
    
    def get_variables(self) -> list:
        """Get the contextual variables of the individual."""
        if not self.anchor_data:
            raise ValueError("No soul anchor data loaded")
        return self.anchor_data.get("contextual_variables", [])
    
    def get_knowledge_domains(self) -> list:
        """Get the knowledge domains of the individual."""
        if not self.anchor_data:
            raise ValueError("No soul anchor data loaded")
        return self.anchor_data.get("knowledge_domains", [])
    
    def get_core_drive(self) -> str:
        """Get the core drive/motivation of the individual."""
        if not self.anchor_data:
            raise ValueError("No soul anchor data loaded")
        return self.anchor_data.get("core_drive", "")
    
    def get_communication_style(self) -> Dict[str, Any]:
        """Get the communication style preferences."""
        if not self.anchor_data:
            raise ValueError("No soul anchor data loaded")
        return self.anchor_data.get("communication_style", {})
    
    def get_all_data(self) -> Dict[str, Any]:
        """Get all soul anchor data."""
        if not self.anchor_data:
            raise ValueError("No soul anchor data loaded")
        return self.anchor_data
