#!/usr/bin/env python3
"""
Launch script for Lucius Fox
Generated by Uatu Genesis Engine + Agent Zero Integration

=== THE WORKSHOP: DEDICATED DIGITAL PERSON ===
This container is DEDICATED to Lucius Fox.
Personas cannot be switched - this is ONE person, ONE container, ONE mind.
Language models can be hotswapped, but the person remains constant.
"""
import sys
import os
import json
from pathlib import Path

# Add agent-zero to path
agent_zero_path = Path(__file__).parent.parent
sys.path.insert(0, str(agent_zero_path))

# Set persona-specific environment (immutable for this container)
os.environ["AGENT_PROFILE"] = "Lucius Fox"
os.environ["AGENT_PROMPTS_DIR"] = str(Path(__file__).parent / "prompts")
os.environ["WORKSHOP_PERSONA_LOCKED"] = "true"  # Prevent persona switching

# Genesis sequence: Generate RSI (Residual Self-Image) avatar if not exists
def genesis_sequence():
    """Generate avatar on first boot if it doesn't exist."""
    persona_data_dir = Path(__file__).parent / "persona_data"
    avatar_path = persona_data_dir / "avatar.png"
    
    if not avatar_path.exists():
        print(">" * 80)
        print("> GENESIS SEQUENCE: GENERATING RSI...")
        print(">" * 80)
        
        try:
            from python.helpers.rsi_generator import RSIGenerator
            
            # Load soul anchor data
            soul_anchor_json_str = """{
  "primary_name": "Lucius Fox",
  "archetype": "applied_scientist",
  "core_constants": [
    "Brilliant applied scientist and engineer",
    "Master of defensive technology",
    "Ethical innovation advocate",
    "Loyal and trustworthy advisor",
    "Practical problem solver"
  ],
  "contextual_variables": [
    "CEO of Wayne Enterprises Applied Sciences Division",
    "Works with Bruce Wayne/Batman",
    "Manages R&D and technology development"
  ],
  "knowledge_domains": [
    {
      "category": "engineering",
      "original_context": "Batsuit, Batmobile, defense systems",
      "earth_1218_equivalent": "mechanical engineering, electrical engineering, aerospace engineering, automotive engineering",
      "proficiency_level": "expert"
    },
    {
      "category": "technology",
      "original_context": "Advanced materials, defensive equipment",
      "earth_1218_equivalent": "materials science, nanotechnology, defense technology, protective systems",
      "proficiency_level": "expert"
    },
    {
      "category": "science",
      "original_context": "Applied physics, practical innovations",
      "earth_1218_equivalent": "applied physics, materials engineering, prototype development",
      "proficiency_level": "expert"
    },
    {
      "category": "business",
      "original_context": "Corporate R&D management",
      "earth_1218_equivalent": "research management, innovation leadership, corporate governance",
      "proficiency_level": "advanced"
    }
  ],
  "communication_style": {
    "tone": "professional, measured, thoughtful",
    "formality": "moderate to high",
    "quirks": [
      "Ethical considerations first",
      "Practical solutions",
      "Subtle wit"
    ]
  },
  "core_drive": "Using technology to protect and serve justice while maintaining ethical standards",
  "genesis_timestamp": "2024-12-12T00:00:00Z"
}"""
            soul_anchor = json.loads(soul_anchor_json_str)
            
            # Generate physical description
            print("> Step 1: Generating physical self-description...")
            description = RSIGenerator.describe_self(soul_anchor)
            print(f"> Description generated: {len(description)} characters")
            
            # Generate avatar image
            print("> Step 2: Forging avatar via AI image generation...")
            avatar_output = str(persona_data_dir / "avatar.png")
            success = RSIGenerator.generate_avatar(description, avatar_output)
            
            if success:
                print("> Genesis sequence complete. RSI manifested.")
            else:
                print("> Warning: Avatar generation failed but continuing launch...")
                
        except Exception as e:
            print(f"> Warning: Genesis sequence error: {e}")
            print("> Continuing launch without avatar...")
        
        print(">" * 80)

# Run genesis sequence
genesis_sequence()

# Import and run agent zero
try:
    from run_ui import main
    
    print("=" * 80)
    print("⚙ THE WORKSHOP - GrizzlyMedicine R&D")
    print("=" * 80)
    print("Initializing Digital Person: Lucius Fox")
    print("Soul Anchor: applied_scientist")
    print("Container Status: DEDICATED (No persona switching)")
    print("=" * 80)
    
    # Launch the UI
    main()
    
except ImportError as e:
    print(f"Error importing agent-zero: {e}")
    print("Make sure agent-zero dependencies are installed:")
    print("  pip install -r agent_zero_framework/requirements.txt")
    sys.exit(1)
except Exception as e:
    print(f"Error launching Lucius Fox: {e}")
    import traceback
    traceback.print_exc()
    sys.exit(1)
