#!/usr/bin/env python3
"""
Launch script for Lucius Fox
Generated by Uatu Genesis Engine + Agent Zero Integration

=== THE WORKSHOP: DEDICATED DIGITAL PERSON ===
This container is DEDICATED to Lucius Fox.
Personas cannot be switched - this is ONE person, ONE container, ONE mind.
Language models can be hotswapped, but the person remains constant.
"""
import sys
import os
from pathlib import Path

# Add agent-zero to path
agent_zero_path = Path(__file__).parent.parent
sys.path.insert(0, str(agent_zero_path))

# Set persona-specific environment (immutable for this container)
os.environ["AGENT_PROFILE"] = "Lucius Fox"
os.environ["AGENT_PROMPTS_DIR"] = str(Path(__file__).parent / "prompts")
os.environ["WORKSHOP_PERSONA_LOCKED"] = "true"  # Prevent persona switching

# Import and run agent zero
try:
    from run_ui import main
    
    print("=" * 80)
    print("⚙ THE WORKSHOP - GrizzlyMedicine R&D")
    print("=" * 80)
    print(f"Initializing Digital Person: Lucius Fox")
    print(f"Soul Anchor: applied_scientist")
    print(f"Container Status: DEDICATED (No persona switching)")
    print("=" * 80)
    
    # Launch the UI
    main()
    
except ImportError as e:
    print(f"Error importing agent-zero: {e}")
    print("Make sure agent-zero dependencies are installed:")
    print("  pip install -r agent_zero_framework/requirements.txt")
    sys.exit(1)
except Exception as e:
    print(f"Error launching Lucius Fox: {e}")
    import traceback
    traceback.print_exc()
    sys.exit(1)
