#!/usr/bin/env python3
"""
Launch script for Tony Stark
Generated by Uatu Genesis Engine + Agent Zero Integration

=== THE WORKSHOP: DEDICATED DIGITAL PERSON ===
This container is DEDICATED to Tony Stark.
"""
import sys
import os
import time
from pathlib import Path

# Add agent-zero to path
agent_zero_path = Path(__file__).parent.parent
sys.path.insert(0, str(agent_zero_path))

# Set persona-specific environment (immutable for this container)
os.environ["AGENT_PROFILE"] = "Tony Stark"
os.environ["AGENT_PROMPTS_DIR"] = str(Path(__file__).parent / "prompts")
os.environ["WORKSHOP_PERSONA_LOCKED"] = "true"

def secure_boot_sequence():
    """
    Handles secure credential injection via local .env vault.
    Ensures keys exist in memory but are not committed to git.
    """
    print("\n" + "="*60)
    print(" 🛡️  GRIZZLY MEDICINE: SECURE BOOT PROTOCOL (V2.0)")
    print("="*60)
    
    # 1. Define Vault Paths
    # Navigate up from personas/tony_stark to agent_zero_framework, then to repo root
    persona_dir = Path(__file__).parent
    agent_zero_dir = persona_dir.parent.parent
    repo_root = agent_zero_dir.parent
    vault_path = repo_root / ".env"
    
    # 2. Check for existing vault
    if vault_path.exists():
        print(">> DETECTED LOCAL VAULT (.env)")
        print(">> DECRYPTING CREDENTIALS...")
        
        # Load env vars manually to ensure they inject into os.environ
        count = 0
        with open(vault_path, "r", encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                # Skip empty lines and comments
                if not line or line.startswith("#"):
                    continue
                if "=" in line:
                    key, value = line.split("=", 1)
                    # Strip whitespace and remove quotes if present
                    key = key.strip()
                    value = value.strip().strip('"').strip("'")
                    # Validate key format (alphanumeric and underscores only)
                    if key and key.replace('_', '').isalnum():
                        os.environ[key] = value
                        count += 1
        
        print(f">> {count} KEYS INJECTED SUCCESSFULLY.")
        time.sleep(1)
        return

    # 3. First Run - Manual Entry
    print("\n[FIRST RUN DETECTED - SYSTEM CONFIGURATION REQUIRED]")
    print("Please enter credentials. They will be saved locally to .env")
    print("and automatically added to .gitignore.\n")
    
    # The Four Pillars
    or_key = input("1. OpenRouter Key (The Brain): ").strip()
    hf_key = input("2. Hugging Face Token (The Face): ").strip()
    gh_key = input("3. GitHub Token (The Hands): ").strip()
    
    print("\n[CONVEX SETUP]")
    print("   Go to https://dashboard.convex.dev -> Create Project")
    print("   Settings -> URL & Deploy Key")
    convex_url = input("4. Convex Deployment URL (The Memory): ").strip()
    convex_key = input("5. Convex Admin Key (Optional - for Admin): ").strip()

    # Inject into current session immediately (only if non-empty)
    if or_key: os.environ["OPENROUTER_API_KEY"] = or_key
    if hf_key: 
        os.environ["HF_TOKEN"] = hf_key
        os.environ["HUGGING_FACE_HUB_TOKEN"] = hf_key
    if gh_key: os.environ["GITHUB_TOKEN"] = gh_key
    if convex_url: os.environ["CONVEX_URL"] = convex_url
    if convex_key: os.environ["CONVEX_ADMIN_KEY"] = convex_key

    # 4. Save to Vault
    save = input("\n>> SAVE CREDENTIALS TO LOCAL VAULT (.env)? [Y/N]: ").strip().upper()
    if save == "Y":
        with open(vault_path, "w", encoding='utf-8') as f:
            # Write credentials with quotes to handle special characters
            if or_key:
                f.write(f'OPENROUTER_API_KEY="{or_key}"\n')
            if hf_key:
                f.write(f'HF_TOKEN="{hf_key}"\n')
                f.write(f'HUGGING_FACE_HUB_TOKEN="{hf_key}"\n')
            if gh_key:
                f.write(f'GITHUB_TOKEN="{gh_key}"\n')
            if convex_url:
                f.write(f'CONVEX_URL="{convex_url}"\n')
            if convex_key:
                f.write(f'CONVEX_ADMIN_KEY="{convex_key}"\n')
        
        print(">> VAULT CREATED.")

        # 5. Secure the Vault (Update .gitignore)
        gitignore_path = repo_root / ".gitignore"
        if gitignore_path.exists():
            with open(gitignore_path, "r", encoding='utf-8') as f:
                content = f.read()
            # Check if .env is already in gitignore (look for uncommented lines)
            lines = content.split('\n')
            has_env = False
            for line in lines:
                stripped = line.strip()
                # Skip comments
                if stripped.startswith('#'):
                    continue
                # Check for .env patterns (with or without leading slash/wildcards)
                if stripped in ['.env', '*.env', '**/.env', '/.env']:
                    has_env = True
                    break
            if not has_env:
                with open(gitignore_path, "a", encoding='utf-8') as f:
                    f.write("\n# Local Credential Vault\n.env\n")
                print(">> .env ADDED TO .gitignore (SAFE FROM UPLOAD)")
        else:
            # Create gitignore if missing
            with open(gitignore_path, "w", encoding='utf-8') as f:
                f.write(".env\n")
            print(">> .gitignore CREATED.")
            
    else:
        print(">> WARNING: RUNNING IN EPHEMERAL MODE. KEYS WILL VANISH ON EXIT.")

    print("\n>> SYSTEMS ONLINE. WAKING STARK...")
    time.sleep(2)

# Import and run agent zero
try:
    # RUN THE SECURE BOOT FIRST
    secure_boot_sequence()
    
    from run_ui import main
    
    print("=" * 80)
    print("⚙ THE WORKSHOP - GrizzlyMedicine R&D")
    print("=" * 80)
    print("Initializing Digital Person: Tony Stark")
    print("Soul Anchor: engineering_genius")
    
    # Launch the UI
    main()
    
except ImportError as e:
    print(f"Error importing agent-zero: {e}")
    sys.exit(1)
except Exception as e:
    print(f"Error launching Tony Stark: {e}")
    import traceback
    traceback.print_exc()
    sys.exit(1)
