#!/usr/bin/env python3
"""
Launch script for Bruce Wayne
Generated by Uatu Genesis Engine + Agent Zero Integration
"""
import sys
import os
from pathlib import Path

# Add agent-zero to path
agent_zero_path = Path(__file__).parent.parent
sys.path.insert(0, str(agent_zero_path))

# Set persona-specific environment
os.environ["AGENT_PROFILE"] = "Bruce Wayne"
os.environ["AGENT_PROMPTS_DIR"] = str(Path(__file__).parent / "prompts")

# Import and run agent zero
try:
    from run_ui import main
    
    print("=" * 80)
    print(f"Initializing Bruce Wayne...")
    print(f"Soul Anchor Loaded: detective_strategist")
    print("=" * 80)
    
    # Launch the UI
    main()
    
except ImportError as e:
    print(f"Error importing agent-zero: {e}")
    print("Make sure agent-zero dependencies are installed:")
    print("  pip install -r agent_zero_framework/requirements.txt")
    sys.exit(1)
except Exception as e:
    print(f"Error launching Bruce Wayne: {e}")
    import traceback
    traceback.print_exc()
    sys.exit(1)
